using Test
using Aqua
using CTBase
using CTModels

# import CTParser: CTParser, @def
# CTParser.set_prefix(:CTModels); # code generated by @def is prefixed by CTModels (not by OptimalControl - the default)

#
include("solution_example.jl")
#include("solution_example_path_constraints.jl")

#
@testset verbose = true showtiming = true "CTModels tests" begin
    for name in (
        :ext_exceptions,
        :aqua,
        :times,
        :control,
        :state,
        :variable,
        :dynamics,
        :objective,
        :constraints,
        :model,
        :ocp,
        :plot,
        :init,
        :export_import,
        :utils,
    )
        @testset "$(name)" begin
            test_name = Symbol(:test_, name)
            println("testing: ", string(name))
            include("$(test_name).jl")
            @eval $test_name()
        end
    end
end
