name = "CTModels"
uuid = "34c4fa32-2049-4079-8329-de33c2a22e2d"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]
version = "0.1.0"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
CTBase = "0.14.0"
DocStringExtensions = "0.9.3"
Parameters = "0.12.3"
julia = "1.10"
