# OCP module includes
include(joinpath(@__DIR__, "dual_model.jl"))
include(joinpath(@__DIR__, "state.jl"))
include(joinpath(@__DIR__, "control.jl"))
include(joinpath(@__DIR__, "variable.jl"))
include(joinpath(@__DIR__, "times.jl"))
include(joinpath(@__DIR__, "dynamics.jl"))
include(joinpath(@__DIR__, "objective.jl"))
include(joinpath(@__DIR__, "constraints.jl"))
include(joinpath(@__DIR__, "time_dependence.jl"))
include(joinpath(@__DIR__, "definition.jl"))
include(joinpath(@__DIR__, "print.jl"))
include(joinpath(@__DIR__, "model.jl"))
include(joinpath(@__DIR__, "solution.jl"))
