using Documenter
using CTModels
using CTBase  # For automatic_reference_documentation
using Plots
using JSON3
using JLD2
using Markdown
using MarkdownAST: MarkdownAST

# ═══════════════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════════════
draft = false  # Draft mode: if true, @example blocks in markdown are not executed

# ═══════════════════════════════════════════════════════════════════════════════
# Load extensions
# ═══════════════════════════════════════════════════════════════════════════════
const CTModelsPlots = Base.get_extension(CTModels, :CTModelsPlots)
const CTModelsJSON = Base.get_extension(CTModels, :CTModelsJSON)
const CTModelsJLD = Base.get_extension(CTModels, :CTModelsJLD)

# to add docstrings from external packages
Modules = [Plots, CTModelsPlots, CTModelsJSON, CTModelsJLD]
for Module in Modules
    isnothing(DocMeta.getdocmeta(Module, :DocTestSetup)) &&
        DocMeta.setdocmeta!(Module, :DocTestSetup, :(using $Module); recursive=true)
end

# ═══════════════════════════════════════════════════════════════════════════════
# Paths
# ═══════════════════════════════════════════════════════════════════════════════
repo_url = "github.com/control-toolbox/CTModels.jl"
src_dir = abspath(joinpath(@__DIR__, "..", "src"))
ext_dir = abspath(joinpath(@__DIR__, "..", "ext"))

# Helper to build absolute paths
src(files...) = [abspath(joinpath(src_dir, f)) for f in files]
ext(files...) = [abspath(joinpath(ext_dir, f)) for f in files]

# Symbols to exclude from documentation (auto-generated by @with_kw, etc.)
const EXCLUDE_SYMBOLS = Symbol[
    :include,
    :eval,
    Symbol("@pack_PreModel"),
    Symbol("@pack_PreModel!"),
    Symbol("@unpack_PreModel"),
    :is_empty,
]

# ═══════════════════════════════════════════════════════════════════════════════
# Build documentation
# ═══════════════════════════════════════════════════════════════════════════════
makedocs(;
    draft=draft,
    remotes=nothing,  # Disable remote links. Needed for DocumenterReference
    warnonly=true,
    sitename="CTModels.jl",
    format=Documenter.HTML(;
        repolink="https://" * repo_url,
        prettyurls=false,
        #size_threshold_ignore=["api.md", "dev.md"],
        #size_threshold=300_000,  # 300 KiB threshold
        assets=[
            asset("https://control-toolbox.org/assets/css/documentation.css"),
            asset("https://control-toolbox.org/assets/js/documentation.js"),
        ],
    ),
    checkdocs=:none,
    pages=[
        "Introduction" => "index.md",
        "Interfaces" => [
            "OCP Tools" => "interfaces/ocp_tools.md",
            "Optimization Problems" => "interfaces/optimization_problems.md",
            "Optimization Modelers" => "interfaces/optimization_modelers.md",
            "Solution Builders" => "interfaces/ocp_solution_builders.md",
        ],
        "API Reference" => [
            # ───────────────────────────────────────────────────────────────────
            # Main module
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTModels => src("CTModels.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="CTModels",
                title_in_menu="CTModels",
                filename="ctmodels",
            ),
            # ───────────────────────────────────────────────────────────────────
            # Core: Types
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[
                    CTModels => src(
                        "core/types.jl",
                        "core/types/ocp_model.jl",
                        "core/types/ocp_components.jl",
                        "core/types/ocp_solution.jl",
                        "core/types/initial_guess.jl",
                        "core/types/nlp.jl",
                    ),
                ],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Types",
                title_in_menu="Types",
                filename="types",
            ),
            # ───────────────────────────────────────────────────────────────────
            # Core: Default & Utils
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTModels => src("core/default.jl", "core/utils.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Default & Utils",
                title_in_menu="Default & Utils",
                filename="default_utils",
            ),
            # ───────────────────────────────────────────────────────────────────
            # OCP: Model (model, definition, time_dependence)
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[
                    CTModels => src(
                        "ocp/model.jl",
                        "ocp/definition.jl",
                        "ocp/time_dependence.jl",
                    ),
                ],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Model",
                title_in_menu="Model",
                filename="model",
            ),
            # ───────────────────────────────────────────────────────────────────
            # OCP: Times
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTModels => src("ocp/times.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Times",
                title_in_menu="Times",
                filename="times",
            ),
            # ───────────────────────────────────────────────────────────────────
            # OCP: State, Control, Variable
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[
                    CTModels => src("ocp/state.jl", "ocp/control.jl", "ocp/variable.jl")
                ],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="State, Control & Variable",
                title_in_menu="State, Control & Variable",
                filename="state_control_variable",
            ),
            # ───────────────────────────────────────────────────────────────────
            # OCP: Dynamics & Objective
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTModels => src("ocp/dynamics.jl", "ocp/objective.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Dynamics & Objective",
                title_in_menu="Dynamics & Objective",
                filename="dynamics_objective",
            ),
            # ───────────────────────────────────────────────────────────────────
            # OCP: Constraints
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTModels => src("ocp/constraints.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Constraints",
                title_in_menu="Constraints",
                filename="constraints",
            ),
            # ───────────────────────────────────────────────────────────────────
            # OCP: Solution & Dual
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTModels => src("ocp/solution.jl", "ocp/dual_model.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Solution & Dual",
                title_in_menu="Solution & Dual",
                filename="solution_dual",
            ),
            # ───────────────────────────────────────────────────────────────────
            # OCP: Print
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTModels => src("ocp/print.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Print",
                title_in_menu="Print",
                filename="print",
            ),
            # ───────────────────────────────────────────────────────────────────
            # Initial Guess
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTModels => src("init/initial_guess.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Initial Guess",
                title_in_menu="Initial Guess",
                filename="initial_guess",
            ),
            # ───────────────────────────────────────────────────────────────────
            # NLP Backends
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[
                    CTModels => src(
                        "nlp/nlp_backends.jl",
                        "nlp/options_schema.jl",
                        "nlp/problem_core.jl",
                        "nlp/discretized_ocp.jl",
                        "nlp/model_api.jl",
                    ),
                ],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="NLP Backends",
                title_in_menu="NLP Backends",
                filename="nlp",
            ),
            # ───────────────────────────────────────────────────────────────────
            # Extension: Plot
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[
                    CTModelsPlots => ext(
                        "CTModelsPlots.jl",
                        "plot.jl",
                        "plot_default.jl",
                        "plot_utils.jl",
                    ),
                ],
                external_modules_to_document=[Plots],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Plot Extension",
                title_in_menu="Plot",
                filename="plot",
            ),
            # ───────────────────────────────────────────────────────────────────
            # Extension: JLD & JSON (combined)
            # ───────────────────────────────────────────────────────────────────
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[
                    CTModelsJSON => ext("CTModelsJSON.jl"),
                    CTModelsJLD => ext("CTModelsJLD.jl"),
                ],
                external_modules_to_document=[CTModels],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="JLD & JSON Extension",
                title_in_menu="JLD & JSON",
                filename="import_export",
            ),
        ],
    ],
)

# ═══════════════════════════════════════════════════════════════════════════════
deploydocs(; repo=repo_url * ".git", devbranch="main")
